version: '3.7'
services:
  function2seq-devcontainer:
    build:
      context: .
    image: "morria/function2seq-devcontainer:latest"
    hostname: "function2seq"
    container_name: "function2seq-devcontainer"
    volumes:
      - "..:/workspace:cached"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
